DROP TABLE IF EXISTS CITY;
CREATE TABLE CITY
(
    CITY_ID   INT NOT NULL AUTO_INCREMENT,
    CITY_NAME VARCHAR(50),
    COUNTRY   VARCHAR(30),
    CREATE_AT TIMESTAMP(6)
);

DROP TABLE IF EXISTS CITY_SEARCH;
CREATE TABLE CITY_SEARCH
(
    CITY_ID   INT NOT NULL,
    SEARCH_AT TIMESTAMP(6)
);

DROP TABLE IF EXISTS TOUR;
CREATE TABLE TOUR
(
    TOUR_ID   INT NOT NULL AUTO_INCREMENT,
    USER_ID   INT NOT NULL,
    CITY_ID   INT NOT NULL,
    START_DATE TIMESTAMP(6),
    END_DATE TIMESTAMP(6)
);